# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /:title.html
exclude: ["Makefile", "README.md", "./_/", "CNAME", "node_modules"]
sass:
  style: compressed

# Site info
url: http://sadiangabay.com/til
title: Today I Learned

# Google analytics
#analytics:
  #hostname: sadiangabay.com
  #id: "UA-57991635-2"

# Collections
collections:
  - authors

# Default variables
defaults:
  - scope:
      path: ""
    values:
      layout: "article"
      tags: []
      author: Jewel Sadiang-abay
